export const site = {
  company: 'Basmni Technologies Pvt. Ltd.',
  tagline: 'Engineering the future of dams, energy transmission and water infrastructure.',
  phone: '+91 93103 34622',
  email: 'info@basmni.com',
  address: '904 New Delhi House, 27 Barakhamba Road, New Delhi - 110001',
  // logoLight: white wordmark for dark backgrounds (header, dark sections)
  // logoDark: dark wordmark for light backgrounds (footer)
  logo: '/images/basmni-logo-light.png',
  logoLight: '/images/basmni-logo-light.png',
  logoDark: '/images/basmni-logo-dark.png',
}

// All site imagery is served locally from /public/images. Keys are referenced
// across pages and content modules, so keep them stable.
export const media = {
  hero: '/images/hero-valley-installation.jpeg',
  dredging: '/images/dredging-intake-structure.jpeg',
  pac: '/images/pac-hydraulic-power-units.jpeg',
  trcm: '/images/trcm-hydraulic-machines.jpeg',
  trcmDamIntakeMachine: '/images/trcm-dam-intake-machine.jpeg',
  trcmIntakeDebrisBand: '/images/trcm-intake-debris-band.jpeg',
  civilTrenchWeirIntake: '/images/civil-trench-weir-intake.jpeg',
  refBhaledhBefore: '/images/ref-bhaledh-before.jpeg',
  refBhaledhAfter: '/images/ref-bhaledh-after.jpeg',
  civilIntakeScreensCanal: '/images/civil-intake-screens-canal.jpeg',
  civilDewateredIntakeBay: '/images/civil-dewatered-intake-bay.jpeg',
  civilTrashRackPanels: '/images/civil-trash-rack-panels.jpeg',
  civilFoundationExcavation: '/images/civil-foundation-excavation.jpeg',
  civilWeirExcavatorRackPanels: '/images/civil-weir-excavator-rack-panels.jpeg',
  civilGatedBarrageGantry: '/images/civil-gated-barrage-gantry.jpeg',
  civilDamSpillwayPiers: '/images/civil-dam-spillway-piers.jpeg',
  civilIntakeTrashRackWall: '/images/civil-intake-trash-rack-wall.jpeg',
  civilIntakeChannelGate: '/images/civil-intake-channel-gate.jpeg',
  spillway: '/images/spillway-debris-boom.jpeg',
  field: '/images/field-crane-installation.jpeg',
  aboutTeamDragflowPump: '/images/about-team-dragflow-pump.jpeg',
  capabilitiesTeam: '/images/capabilities-team-site.jpeg',
  equipmentDamSpillway: '/images/dam-spillway-equipment.jpeg',
  refIndirasagarBefore: '/images/ref-indirasagar-before.jpeg',
  refIndirasagarAfter: '/images/ref-indirasagar-after.jpeg',
  dikrongDredging: '/images/dikrong-dredging.jpeg',
  pipeCraneInstallation: '/images/pipe-crane-installation-site.jpeg',
  civilTruckBuoysMountainRoad: '/images/civil-truck-buoys-mountain-road.jpeg',
  civilPipeStackRiverside: '/images/civil-pipe-stack-riverside.jpeg',
  civilPipeDeliveryTruck: '/images/civil-pipe-delivery-truck.jpeg',
  civilPipesCraneRiverside: '/images/civil-pipes-crane-riverside.jpeg',
  civilPipesCraneHillside: '/images/civil-pipes-crane-hillside.jpeg',
  civilBuoysTruckLoading: '/images/civil-buoys-truck-loading.jpeg',
  civilFlangedPipesTruck: '/images/civil-flanged-pipes-truck.jpeg',
  nimooDredging: '/images/nimoo-dredging.jpeg',
  logBoom: '/images/reservoir-log-boom.jpeg',
  debrisPanorama: '/images/debris-management-panorama.jpeg',
  // Stock photography (real, documentary) filling gaps where a Basmni photo
  // does not exist for the subject.
  pacInfra: '/images/pac-high-voltage-substation.jpeg',
  hydropowerDam: '/images/hydropower-dam-reservoir.jpeg',
  civil: '/images/dam-concrete-civil-construction.jpeg',
  cableDredge: '/images/dredger-pumping-sediment.jpeg',
  remoteDredge: '/images/dredging-barge-excavator.jpeg',
  amphibiousDredge: '/images/amphibious-floating-excavator.jpeg',
  slurryPump: '/images/slurry-submersible-pump.jpeg',
  trashRack: '/images/intake-debris-trash-rack.jpeg',
  fieldInspection: '/images/field-engineering-inspection.jpeg',
  civilSiteReview: '/images/civil-engineering-site-review.jpeg',
  heroAbout: '/images/about-dam-canyon-hero.jpeg',
  heroReferences: '/images/references-dam-crane-hero.jpeg',
  homeIntro: '/images/home-water-infrastructure.jpeg',
  homeHero: '/images/home-hero-hydro-intake.jpeg',
  pacAerial: '/images/pac-substation-aerial.jpeg',
  pacGantry: '/images/pac-transmission-gantry.jpeg',
  pacGis: '/images/pac-gis-switchgear.jpeg',
  pacControl: '/images/pac-control-monitoring.jpeg',
  pacTrench: '/images/pac-trench-installation.jpeg',
  pacInspection: '/images/pac-engineer-inspection.jpeg',
  pacTransmissionGrid: '/images/pac-transmission-grid.jpeg',
  pacCableIndustrial: '/images/pac-cable-industrial.jpeg',
  pacSubstationSwitchyard: '/images/pac-substation-switchyard.jpeg',
  pacHvApplications: '/images/pac-hv-applications.jpeg',
  pacCableTunnel: '/images/pac-cable-tunnel.jpeg',
  dredgeDragflowMachine: '/images/dredge-dragflow-machine.jpeg',
  dredgeSubmersibleHead: '/images/dredge-submersible-head.jpeg',
  dredgePumpPontoon: '/images/dredge-pump-pontoon-reservoir.jpeg',
  dredgeDamShoreline: '/images/dredge-dam-shoreline.jpeg',
  dredgeArchDamAerial: '/images/dredge-arch-dam-aerial.jpeg',
  dredgeReservoirValley: '/images/dredge-reservoir-valley.jpeg',
  dredgeSlurryDischarge: '/images/dredge-slurry-discharge.jpeg',
  dredgeHeroCablePumpDiagram: '/images/dredge-hero-cable-pump-diagram.jpeg',
  dredgeCableBargeClear: '/images/dredge-cable-barge-clear.jpeg',
  dredgeCableDredgeReservoir: '/images/dredge-cable-dredge-reservoir.jpeg',
  dredgeAmphibiousReal: '/images/dredge-amphibious-real.jpeg',
  trcmBlueMachineCloseup: '/images/trcm-blue-machine-closeup.jpeg',
  trcmWireRopeCraneSite: '/images/trcm-wire-rope-crane-site.jpeg',
  floatingPipelineAssemblyYard: '/images/floating-pipeline-assembly-yard.jpeg',
  floatingPipelineFloatsYard: '/images/floating-pipeline-floats-yard.jpeg',
  basmniServiceBoatCraneLift: '/images/basmni-service-boat-crane-lift.jpeg',
  basmniServiceBoatLaunch: '/images/basmni-service-boat-launch.jpeg',
  floatingPipelineCraneAssembly: '/images/floating-pipeline-crane-assembly.jpeg',
  floatingPipelineCraneCrew: '/images/floating-pipeline-crane-crew.jpeg',
  dredgeSlurryPumpRange: '/images/dredge-slurry-pump-range.jpeg',
  dredgeDragflowRender: '/images/dredge-dragflow-render.jpeg',
  dredgeRemoteControlUnit: '/images/dredge-remote-control-unit.jpeg',
  dredgeOperatorRemoteReservoir: '/images/dredge-operator-remote-reservoir.jpeg',
  dredgeSubmersiblePumpStandalone: '/images/dredge-submersible-pump-standalone.jpeg',
  dredgePumpRiggingHose: '/images/dredge-pump-rigging-hose.jpeg',
  trcmHydraulicDredgeCrane: '/images/trcm-hydraulic-dredge-crane.jpeg',
  trcmGantryInstalledSite: '/images/trcm-gantry-installed-site.jpeg',
  trcmRackPanelsCrane: '/images/trcm-rack-panels-crane.jpeg',
  trcmSubmersiblePumpHoses: '/images/trcm-submersible-pump-hoses.jpeg',
  trcmCranePrecastSite: '/images/trcm-crane-precast-site.jpeg',
  trcmSubmersiblePumpCloseup: '/images/trcm-submersible-pump-closeup.jpeg',
  trcmReservoirValleyDeck: '/images/trcm-reservoir-valley-deck.jpeg',
  trcmTeamSiteVisit: '/images/trcm-team-site-visit.jpeg',
  tunnelDesiltingCrew: '/images/tunnel-desilting-crew.jpeg',
  excavatorRockCutting: '/images/excavator-rock-cutting.jpeg',
  shaftDesiltingWorkers: '/images/shaft-desilting-workers.jpeg',
  shaftRebarCageTeam: '/images/shaft-rebar-cage-team.jpeg',
  spillwayTrashRackExcavator: '/images/spillway-trash-rack-excavator.jpeg',
  riverWeirExcavatorWork: '/images/river-weir-excavator-work.jpeg',
  intakeGateExcavatorInstall: '/images/intake-gate-excavator-install.jpeg',
  sandDeliveryTruckSite: '/images/sand-delivery-truck-site.jpeg',
  circularShaftRebarPour: '/images/circular-shaft-rebar-pour.jpeg',
}

export type MediaKey = keyof typeof media
